[book]
authors = ["Arvid Halma"]
language = "en"
title = "MaxRegel - Building a Rule Engine from the Ground Up"
src = "src"
build-dir = "docs"

# Alerts ()
[preprocessor.alerts]

[preprocessor.image-size]
command = "mdbook-image-size"


#[output.pandoc.profile.pdf]
#output-file = "MaxRegel.pdf"
#to = "latex"

#[output.pandoc.profile.epub]
#output-file = "MaxRegel.epub"
#to = "epub"

[output.html]
default-theme = "light"
smart-punctuation = true
mathjax-support = true